--CAN CHE COT OLS_THONGBAO
SELECT VALUE FROM v$option WHERE parameter = 'Oracle Label Security';
SELECT status FROM dba_ols_status WHERE name = 'OLS_CONFIGURE_STATUS'; 

EXEC LBACSYS.CONFIGURE_OLS;
EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;

select * from v$services; 
ALTER USER lbacsys IDENTIFIED BY lbacsys ACCOUNT UNLOCK; 
ALTER PLUGGABLE DATABASE ATBM2024 OPEN READ WRITE;
ALTER SESSION SET CONTAINER = ATBM2024;
SHOW CON_NAME;


-- CAC BUOC TRUOC DO: TAO BANG THONGBAO DE KIEM TRA
--DROP TABLE THONGBAO;
CREATE TABLE THONGBAO(
    MATB INT primary key,
    NOIDUNG VARCHAR2(200),
    THOIGIAN TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
DELETE FROM THONGBAO WHERE MATB=2;
INSERT INTO THONGBAO(MATB,NOIDUNG) VALUES (1, 'DAY LA THONG BAO CHO TRUONG KHOA CO THE DOC TOAN BO DU LIEU');
INSERT INTO THONGBAO(MATB,NOIDUNG) VALUES (2, 'DAY LA THONG BAO CHO TRUONG DON VI CO SO 2 DOC TAT CA LIEN QUAN DEN BO MON HTTT');
INSERT INTO THONGBAO(MATB,NOIDUNG) VALUES (3, 'DAY LA THONG BAO CHO GIAO VU DOC TOAN BO DANH CHO GIAO VU');
INSERT INTO THONGBAO(MATB,NOIDUNG) VALUES (4, 'DAY LA THONG BAO CHO TAT CA TRUONG DON VI');
INSERT INTO THONGBAO(MATB,NOIDUNG) VALUES (5, 'DAY LA THONG BAO CHO SINH VIEN HTTT CO SO 1');
INSERT INTO THONGBAO(MATB,NOIDUNG) VALUES (6, 'DAY LA THONG BAO CHO TRUONG DON VI KHTM CO SO 1');
INSERT INTO THONGBAO(MATB,NOIDUNG) VALUES (7, 'DAY LA THONG BAO CHO TRUONG DON VI KHTM CO SO 1 VA 2');
INSERT INTO THONGBAO(MATB,NOIDUNG) VALUES (8, 'DAY LA THONG BAO CHO TRUONG DON VI HTTT CO SO 1 '); --kiem tra d va e
INSERT INTO THONGBAO(MATB,NOIDUNG) VALUES (9, 'DAY LA THONG BAO CHO SINH VIEN HTTT CO SO 1');
SELECT * FROM THONGBAO;
-- B1: TAO POLICY
EXECUTE SA_SYSDBA.CREATE_POLICY ('OLS_QLK', 'OLS_THONGBAO','NO_CONTROL');
--BEGIN
--  SA_SYSDBA.DROP_POLICY ( 
--    policy_name  => 'OLS_QLK',
--    drop_column  => TRUE);
--END;
--/




--from here, go to QLK
-- B2: DINH NGHIA CAC THANH PHAN CUA NHAN

EXEC SA_COMPONENTS.CREATE_LEVEL('OLS_QLK',100,'SV','SINH VIEN');
EXEC SA_COMPONENTS.CREATE_LEVEL('OLS_QLK',200,'NV','NHAN VIEN');
EXEC SA_COMPONENTS.CREATE_LEVEL('OLS_QLK',300,'GVU','GIAO VU');
EXEC SA_COMPONENTS.CREATE_LEVEL('OLS_QLK',400,'GV','GIANG VIEN');
EXEC SA_COMPONENTS.CREATE_LEVEL('OLS_QLK',500,'TDV','TRUONG DON VI');
EXEC SA_COMPONENTS.CREATE_LEVEL('OLS_QLK',600,'TKHOA','TRUONG KHOA');

EXEC SA_COMPONENTS.CREATE_COMPARTMENT('OLS_QLK',10,'HTTT','HE THONG THONG TIN');
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('OLS_QLK',20,'CNPM','CONG NGHE PHAN MEM');
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('OLS_QLK',30,'KHMT','KHOA HOC MAY TINH');
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('OLS_QLK',40,'CNTT','CONG NGHE THONG TIN');
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('OLS_QLK',50,'TGMT','THI GIAC MAY TINH');
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('OLS_QLK',60,'MMT','MANG MAY TINH');

EXEC SA_COMPONENTS.CREATE_GROUP('OLS_QLK',110,'CS1','CO SO 1');
EXEC SA_COMPONENTS.CREATE_GROUP('OLS_QLK',220,'CS2','CO SO 2');

--EXECUTE SA_COMPONENTS.DROP_GROUP('OLS_QLK',10);

--B3: TAO NHAN DE GAN CHO DU LIEU
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLK', 1000, 'TKHOA');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLK', 970, 'GVU');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLK', 990, 'TDV:HTTT');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLK', 940, 'SV:HTTT:CS1');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLK', 950, 'TDV:KHMT:CS1');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLK', 960, 'TDV:KHMT:CS1,CS2');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLK', 980, 'TDV');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLK', 930, 'SV:HTTT');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLK', 900, 'TDV:HTTT:CS1');

--EXECUTE SA_LABEL_ADMIN.DROP_LABEL('OLS_QLK', 1000000011);
SELECT *FROM DBA_SA_LABELS;


BEGIN
SA_POLICY_ADMIN.APPLY_TABLE_POLICY(
    POLICY_NAME => 'OLS_QLK',
    SCHEMA_NAME => 'C##QLK',
    TABLE_NAME => 'THONGBAO',
    TABLE_OPTIONS => NULL
    );
END;
/
select * from C##QLK.THONGBAO;
UPDATE C##QLK.THONGBAO SET OLS_THONGBAO = CHAR_TO_LABEL('OLS_QLK', 'TKHOA') WHERE MATB =1;
UPDATE C##QLK.THONGBAO SET OLS_THONGBAO = CHAR_TO_LABEL('OLS_QLK', 'TDV:HTTT') WHERE MATB =2;
UPDATE C##QLK.THONGBAO SET OLS_THONGBAO = CHAR_TO_LABEL('OLS_QLK', 'GVU') WHERE MATB =3;
UPDATE C##QLK.THONGBAO SET OLS_THONGBAO = CHAR_TO_LABEL('OLS_QLK', 'TDV') WHERE MATB =4;
UPDATE C##QLK.THONGBAO SET OLS_THONGBAO = CHAR_TO_LABEL('OLS_QLK', 'SV:HTTT:CS1') WHERE MATB =5;
UPDATE C##QLK.THONGBAO SET OLS_THONGBAO = CHAR_TO_LABEL('OLS_QLK', 'TDV:KHMT:CS1') WHERE MATB =6;
UPDATE C##QLK.THONGBAO SET OLS_THONGBAO = CHAR_TO_LABEL('OLS_QLK', 'TDV:KHMT:CS1,CS2') WHERE MATB =7;
UPDATE C##QLK.THONGBAO SET OLS_THONGBAO = CHAR_TO_LABEL('OLS_QLK', 'TDV:HTTT:CS1') WHERE MATB =8;
UPDATE C##QLK.THONGBAO SET OLS_THONGBAO = CHAR_TO_LABEL('OLS_QLK', 'SV:HTTT:CS1') WHERE MATB =9;
commit;
BEGIN
SA_POLICY_ADMIN.REMOVE_TABLE_POLICY(
    POLICY_NAME => 'OLS_QLK',
    SCHEMA_NAME => 'C##QLK',
    TABLE_NAME => 'THONGBAO',
    DROP_COLUMN => FALSE
    );
END;
/
BEGIN
SA_POLICY_ADMIN.APPLY_TABLE_POLICY(
    POLICY_NAME => 'OLS_QLK',
    SCHEMA_NAME => 'C##QLK',
    TABLE_NAME => 'THONGBAO',
    TABLE_OPTIONS => 'READ_CONTROL, WRITE_CONTROL, CHECK_CONTROL'
    );
END;
/
grant select,insert,update,delete on THONGBAO to public;    
SELECT * FROM DBA_SA_LEVELS; 
SELECT * FROM DBA_SA_COMPARTMENTS;
SELECT * FROM DBA_SA_GROUPS;
SELECT * FROM DBA_SA_GROUP_HIERARCHY; 
select * from NHANSU;
--a: Ng??i dùng là Tr??ng khoa có th? ??c ???c toàn b? thông báo.
BEGIN
    SA_USER_ADMIN.SET_USER_LABELS(
        POLICY_NAME =>'OLS_QLK',
        USER_NAME => 'NGAN107',
        MAX_READ_LABEL => 'TKHOA:HTTT,CNPM,MMT,KHMT,TGMT,CNTT:CS1,CS2',
        MAX_WRITE_LABEL => 'TKHOA:HTTT,CNPM,MMT,KHMT,TGMT,CNTT:CS1,CS2'
);
END;
/

--b:gán nhãn cho các Tr??ng b? môn ph? trách C? s? 2 có th? ??c ???c toàn b? thông
--báo. dành cho tr??ng b? môn không phân bi?t v? trí ??a lý.
--gia su ng??i nay o CS2 va duoc gan nhan nhu sau
--khong biet co nen cho no tat ca compartment -> se trung d)
BEGIN
    SA_USER_ADMIN.SET_USER_LABELS(
        POLICY_NAME =>'OLS_QLK',
        USER_NAME => 'HOANG106',
        MAX_READ_LABEL => 'TDV::CS1,CS2',
        MAX_WRITE_LABEL => 'TDV::CS1,CS2'
);
END;
/

--c:01 Giáo v? có th? ??c toàn b? thông báo dành cho giáo v?
BEGIN
    SA_USER_ADMIN.SET_USER_LABELS(
        POLICY_NAME =>'OLS_QLK',
        USER_NAME => 'CHIEN91',
        MAX_READ_LABEL => 'GVU:HTTT,CNPM,MMT,KHMT,TGMT,CNTT:CS1,CS2',
        MAX_WRITE_LABEL => 'GVU:HTTT,CNPM,MMT,KHMT,TGMT,CNTT:CS1,CS2'
);
END;
/

--d: Tao cac loai Truong Don Vi de test
BEGIN
    SA_USER_ADMIN.SET_USER_LABELS(
        POLICY_NAME =>'OLS_QLK',
        USER_NAME => 'DUNG102',
        MAX_READ_LABEL => 'TDV:TGMT,CNPM,MMT,HTTT:CS2,CS1',
        MAX_WRITE_LABEL => 'TDV:TGMT,CNPM,MMT:CS2' 
);
END;
/
BEGIN
    SA_USER_ADMIN.SET_USER_LABELS(
        POLICY_NAME =>'OLS_QLK',
        USER_NAME => 'TUAN101',
        MAX_READ_LABEL => 'TDV:HTTT:CS1',
        MAX_WRITE_LABEL => 'TDV:HTTT:CS1'
);
END;
/

--e: Sinh viên thu?c ngành HTTT h?c ? C? s? 1.
select * from SINHVIEN;
BEGIN
    SA_USER_ADMIN.SET_USER_LABELS(
        POLICY_NAME =>'OLS_QLK',
        USER_NAME => 'KING1',
        MAX_READ_LABEL => 'SV:HTTT:CS1',
        MAX_WRITE_LABEL => 'SV:HTTT:CS1'
);
END;
/

--f: Tr??ng b? môn KHMT ? C? s? 1.
select * from SINHVIEN;
BEGIN
    SA_USER_ADMIN.SET_USER_LABELS(
        POLICY_NAME =>'OLS_QLK',
        USER_NAME => 'NHI103',
        MAX_READ_LABEL => 'TDV:KHMT:CS1',
        MAX_WRITE_LABEL => 'TDV:KHMT:CS1'
);
END;
/

--g: Tr??ng b? môn KHMT ? C? s? 1 và C? s? 2.
--Minh chua co du TDV cho KHMT (nen tao them)
--Tui dang xai TDV cua bo mon khac
select * from SINHVIEN;

BEGIN
    SA_USER_ADMIN.SET_USER_LABELS(
        POLICY_NAME =>'OLS_QLK',
        USER_NAME => 'QUYNH104',
        MAX_READ_LABEL => 'TDV:KHMT:CS1,CS2',
        MAX_WRITE_LABEL => 'TDV:KHMT:CS1,CS2'
);
END;
/
select * from THONGBAO;
select * from NHANSU;
select * from SINHVIEN;

--dong thong bao t5 den GV thuoc MMT,HTTT cua CS2