ALTER PLUGGABLE DATABASE ATBM2024 OPEN READ WRITE;
SET SERVEROUTPUT ON;
--CREATE OR REPLACE PROCEDURE SP_DROP_USERS_LIKE(
--    pattern IN VARCHAR2
--)
--AS
--    CURSOR user_cursor IS
--        SELECT USERNAME
--        FROM ALL_USERS
--        WHERE USERNAME LIKE pattern;
--
--    user_name VARCHAR2(100);
--BEGIN
--    FOR user_rec IN user_cursor LOOP
--        user_name := user_rec.USERNAME;
--        EXECUTE IMMEDIATE 'DROP USER ' || user_name || ' CASCADE';
--        DBMS_OUTPUT.PUT_LINE('User ' || user_name || ' dropped successfully.');
--    END LOOP;
--EXCEPTION
--    WHEN OTHERS THEN
--        RAISE_APPLICATION_ERROR(-20001, 'Error dropping user: ' || SQLERRM);
--END;
--/
--BEGIN
--    SP_DROP_USERS_LIKE('NV%');
--    SP_DROP_USERS_LIKE('SV%');
--END;
--/

CREATE OR REPLACE PROCEDURE SP_GRANT_EXECUTE(
    INP_PROC IN VARCHAR2,
    INP_ROLE IN VARCHAR2
)
AS
    COUNT_ROLES INT;
BEGIN
    SELECT COUNT(*) INTO COUNT_ROLES FROM ROLE_TAB_PRIVS WHERE ROLE = INP_ROLE;

    IF COUNT_ROLES > 0 THEN
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON ' || INP_PROC || ' TO ' || INP_ROLE;
        DBMS_OUTPUT.PUT_LINE('GRANT EXECUTE THANH CONG CHO ' || INP_ROLE);
    ELSE
        DBMS_OUTPUT.PUT_LINE('Role ' || INP_ROLE || ' KHONG CO DUOC EXECUTE ' || INP_PROC);
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;
/
BEGIN
    SP_GRANT_EXECUTE('SP_VIEW_TABLE', 'COMBINED_ROLE');
    SP_GRANT_EXECUTE('SP_ALL_UPDATE_NHANSU', 'COMBINED_ROLE');
END;
/

-- TONG HOP SP INSERT
CREATE OR REPLACE PROCEDURE SP_INSERT_NHANSU(
    INP_HOTEN IN VARCHAR2,
    INP_PHAI IN VARCHAR2,
    INP_NGSINH IN DATE,
    INP_PHUCAP IN NUMBER,
    INP_DT IN VARCHAR2
) AS
    v_manv VARCHAR2(20);
    v_last_name VARCHAR2(100);
    v_max_rownum NUMBER;
BEGIN
    v_last_name := SUBSTR(INP_HOTEN, INSTR(INP_HOTEN, ' ', -1) + 1);

    SELECT MAX(ROWNUM) + 1 INTO v_max_rownum FROM C##QLK.NHANSU;
    
    v_manv := v_last_name || v_max_rownum;

    INSERT INTO C##QLK.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT)
    VALUES (v_manv, INP_HOTEN, INP_PHAI, INP_NGSINH, INP_PHUCAP, INP_DT);
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('Insert successful. MANV: ' || v_manv);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;
/
BEGIN
    SP_GRANT_EXECUTE('SP_INSERT_NHANSU', 'TKHOA');
    SP_GRANT_EXECUTE('SP_INSERT_NHANSU', 'TDV');
    SP_GRANT_EXECUTE('SP_INSERT_NHANSU', 'GV');
    SP_GRANT_EXECUTE('SP_INSERT_NHANSU', 'GVU');
    SP_GRANT_EXECUTE('SP_INSERT_NHANSU', 'NVCB');
    SP_GRANT_EXECUTE('SP_INSERT_NHANSU', 'SV');
END;
/
CREATE OR REPLACE PROCEDURE SP_INSERT_DONVI(
    INP_MADV IN VARCHAR2,
    INP_TENDV IN VARCHAR2,
    INP_TEN IN VARCHAR2
) AS V_MANV C##QLK.NHANSU.MANV%TYPE;
BEGIN
    SELECT MANV INTO V_MANV FROM C##QLK.NHANSU
    WHERE HOTEN = INP_TEN;
    INSERT INTO DONVI VALUES (INP_MADV, INP_TENDV, V_MANV);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Insert successful. MANV: ' || v_manv);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;
/
BEGIN
    SP_GRANT_EXECUTE('SP_INSERT_DONVI', 'TKHOA');
    SP_GRANT_EXECUTE('SP_INSERT_DONVI', 'TDV');
    SP_GRANT_EXECUTE('SP_INSERT_DONVI', 'GV');
    SP_GRANT_EXECUTE('SP_INSERT_DONVI', 'GVU');
    SP_GRANT_EXECUTE('SP_INSERT_DONVI', 'NVCB');
    SP_GRANT_EXECUTE('SP_INSERT_DONVI', 'SV');
END;
/
